begin;

-- updated_dt を自動更新する共通関数
create or replace function public.fn_set_updated_dt()
returns trigger
language plpgsql
as $$
begin
  new.updated_dt := current_timestamp;
  return new;
end;
$$;

-- ユーザー基本情報テーブル
create table public.users (
  id int generated by default as identity,
  user_name varchar(50) not null,
  email varchar(50) not null,
  phone_number char(11),
  postal_code char(7),
  prefecture varchar(20),
  street_address varchar(255),
  building_name varchar(255),
  birth_date date,
  current_attendance_state smallint,
  current_attendance_id int,
  assignment_date date not null,
  created_at timestamptz not null default current_timestamp,
  updated_dt timestamptz not null default current_timestamp,
  constraint pk_users primary key (id),
  constraint uq_users_email unique (email),
  constraint chk_users_phone_number_format check (
    phone_number is null or phone_number ~ '^[0-9]{11}$'
  ),
  constraint chk_users_postal_code_format check (
    postal_code is null or postal_code ~ '^[0-9]{7}$'
  ),
  constraint chk_users_current_attendance_state check (
    current_attendance_state in (1, 2) or current_attendance_state is null
  ),
  constraint chk_users_attendance_state_requires_id check (
    current_attendance_state is null or current_attendance_id is not null
  ),
  constraint chk_users_attendance_id_requires_state check (
    current_attendance_state is not null or current_attendance_id is null
  )
);

-- 認証情報テーブル
create table public.auth (
  id int generated by default as identity,
  user_id int not null,
  password char(6) not null,
  constraint pk_auth primary key (id),
  constraint uq_auth_user_id unique (user_id),
  constraint fk_auth_user_id_users_id
    foreign key (user_id)
    references public.users (id),
  constraint chk_auth_password_length_and_charset check (
    password ~ '^[A-Za-z0-9]{6}$'
  )
);

-- 勤怠テーブル
create table public.attendance (
  id int generated by default as identity,
  user_id int not null,
  work_date date not null,
  work_start_dt timestamptz not null,
  work_end_dt timestamptz,
  updated_dt timestamptz not null default current_timestamp,
  constraint pk_attendance primary key (id),
  constraint fk_attendance_user_id_users_id
    foreign key (user_id)
    references public.users (id),
  constraint chk_attendance_work_end_after_start check (
    work_end_dt is null or work_end_dt >= work_start_dt
  ),
  -- work_date は DB セッションのタイムゾーン基準の日付と一致させる
  constraint chk_attendance_work_date_matches_start check (
    work_date = work_start_dt::date
  )
);

-- 休憩テーブル
create table public.attendance_breaks (
  id int generated by default as identity,
  attendance_id int not null,
  break_start_dt timestamptz not null,
  break_end_dt timestamptz,
  updated_dt timestamptz not null default current_timestamp,
  constraint pk_attendance_breaks primary key (id),
  constraint fk_attendance_breaks_attendance_id_attendance_id
    foreign key (attendance_id)
    references public.attendance (id),
  constraint chk_attendance_breaks_end_after_start check (
    break_end_dt is null or break_end_dt >= break_start_dt
  )
);

-- users と attendance の循環参照を避けるため、attendance 作成後に追加
alter table public.users
  add constraint fk_users_current_attendance_id_attendance_id
  foreign key (current_attendance_id)
  references public.attendance (id);

-- FK 検索や日次検索で使いやすいように補助 index を作成
create index idx_users_current_attendance_id
  on public.users (current_attendance_id);

create index idx_attendance_user_id
  on public.attendance (user_id);

create index idx_attendance_user_id_work_date
  on public.attendance (user_id, work_date);

create index idx_attendance_breaks_attendance_id
  on public.attendance_breaks (attendance_id);

-- 同一ユーザーの進行中勤務は 1 件まで
create unique index uq_attendance_user_id_active
  on public.attendance (user_id)
  where work_end_dt is null;

-- 同一勤務の進行中休憩は 1 件まで
create unique index uq_attendance_breaks_attendance_id_active
  on public.attendance_breaks (attendance_id)
  where break_end_dt is null;

-- updated_dt 自動更新 trigger
create trigger trg_users_set_updated_dt
before update on public.users
for each row
execute function public.fn_set_updated_dt();

create trigger trg_attendance_set_updated_dt
before update on public.attendance
for each row
execute function public.fn_set_updated_dt();

create trigger trg_attendance_breaks_set_updated_dt
before update on public.attendance_breaks
for each row
execute function public.fn_set_updated_dt();

commit;
